### ISSUE TITLE
Character name problem , Lobby name is not staying in game , the player name will be guess_XXX in game 

### ISSUE THREAD

**Issue by ralrigs** [insthync/BattleIOMasterServer#2]

**Comment by insthync** [comment]
Please try new version, It have been fixed

**Comment by ralrigs** [comment]
nope i added latest version i still have the problem, its working in the normal scene but not on the battle scene , the name change to Guess_XXX

**Comment by ralrigs** [comment]
ok good but now when you go back to lobby player name go back to the last attribute you added in the battle scene ADDHP in for example, sorry for late reply

**Comment by ralrigs** [comment]
Lol NVM sorry for late close also finnaly fixed many times ago ...  was from a previous hack try on name 	PlayerSave.SetPlayerName (name); and i declared name ... but name is ever used ...
and it was conflict with 
character.CmdAddAttribute(name); in game ... 
sorry for late issue close again
